# BungeeCord Socket configuration, required for sending information
# between servers without the need for online players on each
# sender and recipient
Socket:
  # Whether the BungeeCord Socket is enabled and should automatically attempt to
  # connect on server startup.
  Enabled: false
  # The IP address that is hosting a DepenizenBungee socket server.
  IP Address: "bungee.mcmonkey.org"
  # The port at the IP address that is hosting a DepenizenBungee socket server.
  Port: 25578
  # The password to connect with. Please leave this in "quotes" to keep
  # YAML from thinking it's an invalid string (for example, if it's all numbers).
  Password: "MySecretPassword"
  # The name to connect with. Used for the Bungee dServer object.
  # This does not have to be the same name that Bungee itself
  # recognizes, but it is recommended to use that for consistency.
  Name: "MyServer1"
  # The duration of inactivity that the client will send a ping
  # packet to the server after.
  Ping Delay: "30s"
  # The duration that this client should wait after sending a ping
  # packet before disconnecting and attempting to reconnect.
  Ping Timeout: "30s"
  # The duration to wait between attempts at reconnecting to the socket.
  Reconnection Delay: "10s"
  # The amount of times the socket should attempt to reconnect to the socket
  # before giving up.
  Reconnection Attempts: 10
