name: Depenizen
authors: ['The DenizenScript Team']
version: ${project.version} (build ${BUILD_NUMBER})
main: com.denizenscript.depenizen.bukkit.Depenizen
depend: [Denizen]

api-version: 1.13

softdepend:
    - mcMMO
    - Towny
    - Factions
    - Votifier
    - Jobs
    - Heroes
    - pvparena
    - WorldEdit
    - WorldGuard
    - Essentials
    - pvpstats
    - HyperConomy
    - SkillAPI
    - Prism
    - TerrainControl
    - PlotMe
    - PlotSquared
    - SimpleClans
    - MobArena
    - ASkyBlock
    - NoCheatPlus
    - MythicMobs
    - Sentinel
    - Shopkeepers
    - GriefPrevention
    - Quests
    - PlaceholderAPI
    - Residence
    - AreaShop
    - LibsDisguises
    - OpenTerrainGenerator
    - PlayerPoints
    - LuckPerms
    - EffectLib
    - BossShop
    - Vampire
    - NoteBlockAPI
    - MagicSpells
