name: Depenizen
authors: [Morphan1]
version: ${project.version} (build ${BUILD_NUMBER})
main: com.denizenscript.depenizen.bukkit.DepenizenPlugin
depend: [Denizen]
softdepend: [mcMMO, BattleNight, Towny, Factions, Votifier, Jobs, Heroes, pvparena, WorldEdit, WorldGuard, Essentials, pvpstats, HyperConomy, SkillAPI, Prism, TerrainControl, PlotMe, SimpleClans, MobArena, ASkyBlock, NoCheatPlus, MythicMobs, ShopKeepers, GriefPrevention, Quests, PlaceholderAPI, Residence, dtlTraders, AreaShop]

commands:
    depenizen:
        description: Prints out the current Depenizen version.
        usage: /depenizen

permissions: {}
